# Generated by Django 4.1.3 on 2022-11-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Person',
        ),
    ]
