# Generated by Django 4.1.3 on 2022-11-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_person_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name', 'age', 'created']},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
